package cmd

var positivetests = []string{
	"9",
	"9 ~/.local/9/ help",
	"9 help",
	"9 ~/.local/9/ h",
	"9 h",
	"9 ~/.local/9/ cli",
	"9 cli",
	"9 ~/.local/9/ c",
	"9 c",
	"9 ~/.local/9/ listcommands",
	"9 listcommands",
	"9 ~/.local/9/ l",
	"9 l",
	"9 ~/.local/9/ rpc getinfo",
	"9 rpc getinfo",
	"9 ~/.local/9/ r getinfo",
	"9 r getinfo",
	"9 ~/.local/9/ node",
	"9 node",
	"9 ~/.local/9/ n",
	"9 n",
	"9 ~/.local/9/ shell",
	"9 shell",
	"9 ~/.local/9/ s",
	"9 s",
	"9 ~/.local/9/ factory",
	"9 factory",
	"9 ~/.local/9/ new",
	"9 new",
	"9 ~/.local/9/ 4 new",
	"9 new 19",
	"9 ~/.local/9/ new data",
	"9 new datadir",
	"9 ~/.local/9/ new data",
	"9 new 4 data ",
	"9 ~/.local/9/ 4 data new",
	"9 data 4 new",
	"9 ~/.local/9/ testy copy 3",
	"9 3 copy testy",
	"9 ~/.local/9/ test",
	"9 testy",
	"9 ~/.local/9/ test 2",
	"9 9 testy",
	"9 ~/.local/9/ log/path/ 5 test",
	"9 test 10 log/path/here/",
	"9 ~/.local/9/ test testy 9",
	"9 testy test 5",
	"9 ~/.local/9/ 5 test /tmp/logpath testy ",
	"9 /tmp/log/ 5 testy test",
}
